'use strict';
const $=id=>document.getElementById(id);
function apiFetch(url,options={}){return fetch(url,{...options,headers:{...options.headers,'X-Pair-Token':sessionStorage.getItem('vault-pair')||''}});}
const names={ANDREW_PANTON:'Andrew Panton',GAVIN_FREE:'Gavin Free',GEOFF_RAMSEY:'Geoff Ramsey',ERIC_BAUDOUR:'Eric Baudour',NICK_SCHWARTZ:'Nick Schwartz'};
let rows=[],current=null,token='',busy=false,clipEnd=0,dirty=false,newIds=new Set(),archiveEpisodes=[];
function message(text){$('status').textContent=text;}
for(const id of ['speaker','secondary']){const blank=new Option(id==='speaker'?'Choose after listening':'None','');$(id).add(blank);for(const [value,name]of Object.entries(names))$(id).add(new Option(name,value));}
function nav(){const term=$('search').value.toLowerCase();$('queue').replaceChildren();for(const row of rows.filter(r=>JSON.stringify(r.quote).toLowerCase().includes(term))){const b=document.createElement('button'),small=document.createElement('small'),text=document.createElement('span');small.textContent=`${newIds.has(row.quote.id)?'New · ':''}${row.quote.show} · Episode ${row.quote.episode}`;text.textContent=row.quote.quote;b.append(small,text);b.setAttribute('aria-current',String(current?.quote.id===row.quote.id));b.onclick=()=>{if(!busy)select(row);};$('queue').append(b);}}
function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function select(row){dirty=false;current=row;const q=row.quote,s=row.suggestion;$('audio').pause();$('video').replaceChildren();$('audio').hidden=true;$('review').hidden=false;$('empty').hidden=true;$('form').reset();$('episode').textContent=`${q.show} · Episode ${q.episode} · ${q.id}`;$('preview').textContent=`“${q.quote}”`;$('quality').hidden=!q.quality;if(q.quality)$('quality').textContent=`Editorial score: ${q.quality.score}/100 · ${q.quality.reasons.join(' · ')}. Rule-based screening, not speaker confidence.`;$('suggestion').textContent=s.speaker?`Suggested: ${names[s.speaker]} · ${s.score}% text agreement`:'Speaker: unknown · Confidence not available';$('basis').textContent=s.basis;$('existing').textContent=q.speaker?`Draft credit: ${names[q.speaker]||q.speaker} — not verified`:'';$('quote').value=q.quote;$('speaker').value=s.speaker||'';$('secondary').value=s.secondarySpeaker||'';$('show').value=q.show;$('number').value=q.episode;$('title').value=q.episodeTitle;$('videoid').value=q.youtubeVideoId||'';$('seconds').value=q.timestampSeconds??'';$('tags').value=(q.weatherTags||[]).join(', ');$('confirmed').checked=false;$('provider').value=q.playbackProvider||(!q.youtubeVideoId&&q.show==='FF'&&archiveEpisodes.some(r=>r.episode===q.episode)?'rtarchive':'youtube');const recording=archiveEpisodes.find(r=>r.id===q.archiveVideoId)||archiveEpisodes.find(r=>q.show==='FF'&&r.episode===q.episode);if(recording)$('archive-id').value=recording.id;const url=safeUrl(q.source?.url||q.listenUrl);$('source').hidden=!url;if(url)$('source').href=url;$('playnote').textContent=row.audioUrl?'Podcast audio is available. Its segment timing may differ from YouTube.':'Enter or check the YouTube video and start time to preview. The source link can help locate the moment.';updateProvider();nav();}
function parseStamp(s){return(s||'0').split(':').reduce((n,p)=>n*60+Number(p),0);}
$('audio').addEventListener('timeupdate',()=>{if(clipEnd&&$('audio').currentTime>=clipEnd)$('audio').pause();});
$('play').onclick=()=>{if(!current)return;const vid=$('videoid').value.trim(),raw=$('seconds').value;const start=Number(raw);$('audio').pause();$('video').replaceChildren();if($('provider').value==='rtarchive'){const r=archiveEpisodes.find(x=>x.id===$('archive-id').value);if(!r||raw===''||!Number.isInteger(start)||start<0||start>86400)return message('Choose an archive recording and enter a valid start time (0–86400 seconds).');const a=$('audio');a.hidden=false;a.src=r.mediaUrl;clipEnd=start+35;a.onloadedmetadata=()=>{a.currentTime=start;a.play().catch(()=>message('Tap play to start the archive recording.'));};a.onerror=()=>message('Archive playback unavailable. Open the recording link instead.');a.load();$('source').href=r.url+'?t='+start;$('source').hidden=false;$('playnote').textContent='RT Archive recording preview. Check the time against this recording, not a YouTube upload.';return;}if(/^[A-Za-z0-9_-]{11}$/.test(vid)&&raw!==''&&Number.isInteger(start)&&start>=0&&start<=86400){$('audio').hidden=true;const frame=document.createElement('iframe');frame.title='Quote playback preview';frame.allow='autoplay; encrypted-media';frame.src=`https://www.youtube-nocookie.com/embed/${vid}?start=${start}&end=${start+35}&autoplay=1`;frame.allowFullscreen=true;$('video').append(frame);$('playnote').textContent='YouTube preview. If embedding is unavailable, use the source link to listen.';}else if(current.audioUrl){const a=$('audio');a.hidden=false;a.src=current.audioUrl;const begin=Math.max(0,parseStamp(current.quote.source?.audioSegmentTimestamp)-5);clipEnd=begin+35;a.onloadedmetadata=()=>{a.currentTime=begin;a.play().catch(()=>message('Tap the audio play button to start.'));};a.onerror=()=>message('Audio could not load. Open the source link to listen.');a.load();$('playnote').textContent='35 seconds of podcast audio around the source segment. Verify YouTube timing separately.';}else message('Add the YouTube video ID and start time, or open the source link.');};
$('skip').onclick=()=>{if(rows.length&&!busy)select(rows[(rows.indexOf(current)+1)%rows.length]);};
$('search').oninput=nav;
async function load(addedIds=[]){try{const r=await apiFetch('/api/queue');if(r.status===401){const code=prompt('Enter the pairing code shown on your Mac:');if(!code)throw Error('Pairing cancelled. Reload to try again.');const paired=await apiFetch('/api/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const result=await paired.json();if(!paired.ok)throw Error(result.error);sessionStorage.setItem('vault-pair',result.token);return load();}if(!r.ok)throw Error('Could not load queue');const data=await r.json();newIds=new Set(addedIds);archiveEpisodes=data.archiveEpisodes||[];$('archive-id').replaceChildren();for(const r of archiveEpisodes)$('archive-id').add(new Option(`FF ${r.episode} · ${r.title}`,r.id));rows=data.rows.sort((a,b)=>Number(newIds.has(b.quote.id))-Number(newIds.has(a.quote.id)));token=data.token;$('counts').textContent=`${rows.length} waiting · ${data.approved} approved`;if(rows.length)select(rows[0]);else{$('review').hidden=true;$('empty').hidden=false;$('empty').textContent='All caught up. Click Transcribe next episode to collect more candidates.';}nav();}catch(e){message(e.message);}}
function whisperButtons(running){$('whisper-1').hidden=running;$('whisper-5').hidden=running;$('whisper-stop').hidden=!running;}
async function pollWhisper(){
 try{const r=await apiFetch('/api/whisper');const job=await r.json();if(!r.ok)throw Error(job.error);
  if(job.running){whisperButtons(true);message(`Transcribing episode ${Math.min(job.done+1,job.total)} of ${job.total}: ${job.current} · ${job.added} candidate(s) so far. Keep this Mac awake; you can keep reviewing.`);setTimeout(pollWhisper,4000);return;}
  whisperButtons(false);if(job.message){await load(job.addedIds||[]);message(job.message);}
 }catch(error){whisperButtons(false);message(error.message);}
}
async function startWhisper(count){
 if(busy)return;
 try{const r=await apiFetch('/api/whisper',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify({count})});const job=await r.json();if(!r.ok)throw Error(job.error);whisperButtons(true);message('Reading the playlist…');setTimeout(pollWhisper,2000);}
 catch(error){message(error.message);}
}
$('whisper-1').onclick=()=>startWhisper(1);
$('whisper-5').onclick=()=>startWhisper(5);
$('whisper-stop').onclick=async()=>{await apiFetch('/api/whisper/stop',{method:'POST',headers:{'X-Review-Token':token}});$('whisper-stop').hidden=true;message('Stopping after the current episode…');};
$('form').addEventListener('input',e=>{dirty=true;if(e.target.id!=='confirmed')$('confirmed').checked=false;});
$('form').onsubmit=async e=>{e.preventDefault();if(busy||!current)return;busy=true;$('approve').disabled=true;$('approve').textContent='Publishing…';const q=current;const edits={quote:$('quote').value.trim(),speaker:$('speaker').value,secondarySpeaker:$('secondary').value,show:$('show').value,episode:Number($('number').value),episodeTitle:$('title').value.trim(),youtubeVideoId:$('videoid').value.trim(),playbackProvider:$('provider').value,archiveVideoId:$('archive-id').value,timestampSeconds:Number($('seconds').value),weatherTags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),confirmed:$('confirmed').checked};try{const r=await apiFetch('/api/approve',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify({id:q.quote.id,fingerprint:q.fingerprint,edits})});const data=await r.json();if(!r.ok)throw Error(data.error);message(data.message);await load();}catch(e){message(e.message);}finally{busy=false;$('approve').disabled=false;$('approve').textContent='Approve & publish';}};
load().then(pollWhisper);

$('add').onclick=()=>{if(!busy){$('add-form').reset();$('add-error').textContent='';$('add-dialog').showModal();}};
$('cancel-add').onclick=()=>{if(!busy)$('add-dialog').close();};
$('add-dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('add-form').onsubmit=async e=>{
 e.preventDefault();if(busy)return;
 if(dirty&&!confirm('Save this new draft and leave the unsaved review?'))return;
 busy=true;$('save-draft').disabled=true;$('save-draft').textContent='Saving…';$('add-error').textContent='';
 try{const response=await apiFetch('/api/drafts',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify({quote:$('new-quote').value,show:$('new-show').value,episode:Number($('new-episode').value),episodeTitle:$('new-title').value,sourceUrl:$('new-source').value})});const data=await response.json();if(!response.ok)throw Error(data.error);$('add-dialog').close();$('search').value='';await load();const added=rows.find(r=>r.quote.id===data.id);if(added)select(added);message(data.message);}
 catch(error){$('add-error').textContent=error.message;}
 finally{busy=false;$('save-draft').disabled=false;$('save-draft').textContent='Save draft';}
};

$('remove').onclick=async()=>{
 if(busy||!current)return;
 const removed=current, next=rows[rows.indexOf(current)+1]||rows[0];
 busy=true;$('remove').disabled=true;$('remove').textContent='Removing…';
 try{const response=await apiFetch('/api/remove',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify({id:removed.quote.id,fingerprint:removed.fingerprint})});const result=await response.json();if(!response.ok)throw Error(result.error);await load();const nextRow=rows.find(r=>r.quote.id===next?.quote.id);if(nextRow)select(nextRow);message(result.message);}
 catch(error){message(error.message);}
 finally{busy=false;$('remove').disabled=false;$('remove').textContent='Remove quote';}
};

function updateProvider(){const archive=$('provider').value==='rtarchive';$('archive-field').hidden=!archive;$('youtube-field').hidden=archive;$('videoid').required=!archive;if(archive){$('playnote').textContent='F**kFace 1–56: archived recordings available; transcripts are not available in this source. Enter a recording time to preview.';const r=archiveEpisodes.find(x=>x.id===$('archive-id').value);if(r){$('source').href=r.url;$('source').hidden=false;}}}
$('provider').onchange=()=>{$('audio').pause();$('audio').hidden=true;$('video').replaceChildren();$('seconds').value='';$('confirmed').checked=false;if($('provider').value==='rtarchive')$('archive-id').onchange();else{$('source').hidden=true;$('playnote').textContent='Enter the YouTube video ID and verify its start time.';}updateProvider();};
$('archive-id').onchange=()=>{$('audio').pause();$('audio').onloadedmetadata=null;$('audio').removeAttribute('src');$('audio').load();$('audio').hidden=true;$('video').replaceChildren();dirty=true;const r=archiveEpisodes.find(x=>x.id===$('archive-id').value);if(r){$('show').value='FF';$('number').value=r.episode;$('title').value=r.title;$('seconds').value='';$('confirmed').checked=false;updateProvider();}};
